name: google_maps_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  flutter_config: ^2.0.2
  image_picker: ^1.0.4
  geolocator: ^10.0.0
  google_maps_flutter: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner:
  mobx_codegen:

flutter:
  uses-material-design: true

  assets:
    - assets/map/